---
# tasks file for neo4j

- name: install systems packages
  yum:
    name: 
      - firewalld
      - http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: latest

- name: enable and start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: import neo4j gpg key
  rpm_key:
    state: present
    key: https://debian.neo4j.org/neotechnology.gpg.key

- name: add neo4j repository
  yum_repository:
    name: neo4j
    description: neo4j repository
    file: neo4j
    baseurl: https://yum.neo4j.org/stable
    gpgcheck: yes
    enabled: yes
    
- name: install wget
  yum:
    name:
     - wget

- name: install neo4j enterprise
  shell: NEO4J_ACCEPT_LICENSE_AGREEMENT=yes yum -y install neo4j-enterprise

- name: start and enable neo4j service
  service:
    name: neo4j
    state: started
    enabled: yes

- name: open neo4j data ports
  firewalld:
    port: "{{item}}/tcp"
    zone: public
    immediate: yes
    permanent: yes
    state: enabled
  loop:
    - 7474
    - 7473
    - 7687

- name: download neo4j-graphql plugins
  get_url:
    url: https://github.com/neo4j-graphql/neo4j-graphql/releases/download/{{graphql_version}}/neo4j-graphql-{{graphql_version}}.jar
    dest: "{{neo4j_home}}/plugins"
    owner: neo4j
    group: neo4j

- name: add graphql configuration
  lineinfile:
    path: /etc/neo4j/neo4j.conf
    line: 'dbms.unmanaged_extension_classes=org.neo4j.graphql=/graphql'
    regex: 'dbms.directories.data=/var/lib/neo4j/data'
    insertbefore: 'BOF'
  notify: restart neo4j

- name: allow connection from external addresses
  lineinfile:
    path: /etc/neo4j/neo4j.conf
    line: 'dbms.connectors.default_listen_address=0.0.0.0'
    regex: '#dbms.connectors.default_listen_address=0.0.0.0'
  notify: restart neo4j
