---
# tasks file for ecs-agent

#set local routing 
- name: set localhost routing
  sysctl:
    name: net.ipv4.conf.all.route_localnet
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: install iptables
  yum:
    name: 
      - iptables-services
    state: present

- name: start iptables service
  service:
    name: iptables
    state: started
    enabled: yes

- name: configure ecs-agent routing
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination: 169.254.170.2 
    destination_port: 80
    jump: DNAT
    to_destination: 127.0.0.1:51679
    comment: configure nat

- name: configure ecs-agent redirect 
  iptables:
    table: nat
    chain: OUTPUT
    protocol: tcp
    match: tcp
    destination: 169.254.170.2 
    destination_port: '80'
    jump: REDIRECT
    to_ports: '51679'
    comment: Redirect web traffic to port 51679

- name: save iptables
  command: service iptables save
  ignore_errors: yes

- name: reload iptables
  command: service iptables reload
  ignore_errors: yes

- name: create ecs directory
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "/etc/ecs"
    - "/var/log/ecs"
    - "/var/lib/ecs/data"

- name: copy file ecs.config to /etc/ecs/ecs.config
  template:
    src: ecs.config.j2
    dest: /etc/ecs/ecs.config

- name: start ecs agent container
  docker_container:
    name: ecs-agent
    detach: true
    restart_policy: on-failure
    volumes:
      - "/var/run:/var/run"
      - "/var/log/ecs/:/log"
      - "/var/lib/ecs/data:/data"
      - "/etc/ecs:/etc/ecs"
    network_mode: host
    env_file: /etc/ecs/ecs.config
    image: amazon/amazon-ecs-agent:latest
    state: started
    