---
# tasks file for roles/newrelic
- name: setup newrelic repo
  yum_repository:
    name: newrelic-infra
    description: Newrelic infrastruture repository
    baseurl: https://download.newrelic.com/infrastructure_agent/linux/yum/el/7/x86_64/

- name: update yum cache
  command: yum makecache
  args:
    warn: no

- name: install newrelic-infra
  yum:
    name:
      - libcap
      - newrelic-infra 
  environment:
    NRIA_MODE: PRIVILEGED
    NRIA_LICENSE_KEY: "{{ }}"

  notify: restart newrelic-infra

  # https://download.newrelic.com/infrastructure_agent/linux/yum/el/7/x86_64/newrelic-infra.repo

